apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    load_module modules/ngx_http_stub_status_module.so;

    server {
        listen 80;
        # ... other Nginx configuration

        location /metrics {
            stub_status on;
        }
    }