apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9113"
    spec:
      containers:
        - name: nginx-exporter
          image: nginx/nginx-prometheus-exporter # Or your custom image
          ports:
            - containerPort: 9113
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
        - name: nginx
          image: nginx # Or your custom image
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
