apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx # Replace with your Nginx namespace
spec:
  selector:
    app: nginx # Match the label in your deployment
  type: NodePort # Or LoadBalancer, depending on your access needs
  ports:
    - port: 80
      targetPort: 80
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter
  namespace: nginx # Replace with your Nginx namespace
spec:
  selector:
    app: nginx-exporter # Match the label in your deployment
  type: NodePort # Or LoadBalancer, depending on your access needs
  ports:
    - port: 9113
      targetPort: 9113
      protocol: TCP
      name: metrics
